books = [
    {
        "id": 1,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt",
        "publisher": "Addison-Wesley",
        "publish_date": "1999-10-30",
        "page_count": 352,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "publish_date": "2008-08-01",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Introduction to Algorithms",
        "author": "Thomas H. Cormen",
        "publisher": "MIT Press",
        "publish_date": "2009-07-31",
        "page_count": 1312,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Design Patterns",
        "author": "Erich Gamma",
        "publisher": "Addison-Wesley",
        "publish_date": "1994-10-31",
        "page_count": 395,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Deep Learning",
        "author": "Ian Goodfellow",
        "publisher": "MIT Press",
        "publish_date": "2016-11-18",
        "page_count": 800,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Artificial Intelligence: A Modern Approach",
        "author": "Stuart Russell",
        "publisher": "Pearson",
        "publish_date": "2020-04-28",
        "page_count": 1152,
        "language": "English",
    },
]
